more status checks

diff --git a/.github/workflows/status-checks.yaml b/.github/workflows/status-checks.yaml
--- a/.github/workflows/status-checks.yaml
+++ b/.github/workflows/status-checks.yaml
@@ -7,11 +7,16 @@ jobs:
     steps:
     - name: Step 1
       run: sleep 20
-    - name: Runs on Failure
+    # - name: Runs on Failure
+    #   run: exit 1
+    - name: Step 2
+      id: step-2
       run: exit 1
     - name: Runs on Failure
-      if: failure()
-      run: echo 'Runs only on failure'
+      # if: failure()
+      if: failure() && steps.step-2.conclusion == 'failure'
+      run: echo 'Step 2 has failed'
+      # run: echo 'Runs only on failure'
     - name: Runs on Success
       if: success()
       run: echo 'Runs on Success'
